version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/docker-cicd:latest
    container_name: spring-app
    expose:
      - "8080"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always